# Build steps
steps:
  # Backend builds
  - script: dotnet restore
    displayName: "backend: install dependencies"
  # - script: dotnet ef database update
  #   displayName: "backend: migrate database"
  - script: dotnet build
    displayName: "backend: build"
  - script: dotnet test
    displayName: "backend: test"
    workingDirectory: backend-test
