# Build steps
steps:
  # Backend builds
  - script: dotnet restore
    displayName: "backend: install dependencies"
  # - script: dotnet ef database update
  #   displayName: "backend: migrate database"
  - script: dotnet build
    displayName: "backend: build"

  # Frontend builds
  - script: npm install
    workingDirectory: "frontend"
    displayName: "frontend: install dependencies"
  - script: npm run build
    workingDirectory: "frontend"
    displayName: "frontend: build resources"

  # Docker container builds
  - script: 'docker rm -f $(docker ps -aq) && docker rmi -f $(docker images -aq)'
    displayName: "docker: clean environment"
  - script: './build'
    workingDirectory: "docker"
    displayName: "docker: build containers"
