# Build steps
steps:
  # Backend builds
  - script: dotnet restore
    displayName: "backend: install dependencies"
  # - script: dotnet ef database update
  #   displayName: "backend: migrate database"
  - script: dotnet build
    displayName: "backend: build"

  - task: PublishBuildArtifacts@1
    displayName: "Build Artifacts"
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: drop
      publishLocation: Container

    # # Docker container builds
    # - script: './clean'
    #   workingDirectory: "docker"
    #   displayName: "docker: clean environment"
    # - script: './build'
    #   workingDirectory: "docker"
    #   displayName: "docker: build containers"
    # - script: './startd'
    #   workingDirectory: "docker"
    #   displayName: "docker: start stack"
    # - script: './startd && sleep 1m'
    #   workingDirectory: "docker"
    #   displayName: "docker: start stack (wait 1m)"
    # - script: 'curl -f http://localhost:80/'
    #   workingDirectory: "docker"
    #   displayName: "docker: test HTTP request to stack"
    # - script: './stop'
    #   workingDirectory: "docker"
    #   displayName: "docker: stop stack"
    # - script: './clean'
    #   workingDirectory: "docker"
    #   displayName: "docker: clean environment"
