# Build steps
steps:
  # Backend builds
  - script: dotnet restore
    displayName: "backend: install dependencies"
  # - script: dotnet ef database update
  #   displayName: "backend: migrate database"
  - script: dotnet build
    displayName: "backend: build"

  # Frontend builds
  - script: npm prune
    workingDirectory: "frontend"
    displayName: "frontend: clean environment"
  - script: npm install
    workingDirectory: "frontend"
    displayName: "frontend: install dependencies"
  - script: npm run build
    workingDirectory: "frontend"
    displayName: "frontend: build resources"

  # Docker container builds
  - script: './build'
    workingDirectory: "docker"
    displayName: "docker: build containers"
  - script: './clean'
    workingDirectory: "docker"
    displayName: "docker: clean environment"
