#!/bin/bash

# Immediately stop the script if an error occurred
set -e

# Change into the application directory
cd ./webapp

# Restore dependencies
echo "Restoring application dependencies..."
dotnet restore

# Run database migrations
echo "Migrating database..."
dotnet ef database update

# Run the application
echo "Starting the application..."
dotnet run
