#!/bin/sh

# Immediately stop the script if an error occurred
set -e

# Change into the containers directory
cd ../

# Build the dotnet image
echo "Building dotnet image..."
docker build -t schedule-dotnet:snapshot -f ./docker/containers/Dockerfile.dotnet --no-cache .

# Build the application image
echo "Building application image..."
docker build -t schedule-app:snapshot -f ./docker/containers/Dockerfile.app --no-cache .

cd ..
