#!/bin/sh

# Immediately stop the script if an error occurred
set -e

# Build the docker image
echo "Start image build process..."
./build

# Create an image artifact
echo "Create artifact for release image snapshot..."
mkdir -p ../artifact
docker save schedule-app:snapshot -o ../artifact/image-artifact.tar.gz

echo "Done"
