#!/bin/sh

# Immediately stop the script if an error occurred
set -e

# Build the docker image
echo "Starting image build process..."
./build

# Create an image artifact
mkdir -p ../artifact
docker save scheduling-app:snapshot -o ../artifact/image-artifact.tar.gz

echo "Done"
