version: "2"

services:
  app:
    image: 'schedule-app:latest'
    ports:
      - '80:80'
      - '443:443'
      - '5000:5000'
    depends_on:
      - "db"
    volumes:
      - '../:/app'
    networks:
      - scheduleapp
  db:
    image: 'microsoft/mssql-server-linux'
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Secret1234
    volumes:
      - 'dbdata:/mnt/drive'
    networks:
      - scheduleapp
    restart: on-failure

volumes:
  dbdata:

networks:
  scheduleapp:
