version: "3.2"

services:
  app:
    image: 'timvisee/hhs-p11-schedulingapp:release-55'
    ports:
      - "80:5000"
      - "5000:5000"
    environment:
      DATABASE_HOST: "schedulingapp.visee.me"
      DATABASE_DATABASE: "production"
      DATABASE_USER: "sa"
      DATABASE_PASSWORD: "Secret1234!"
      WEB_HOSTS: "http://*:80,http://*:5000"
    depends_on:
      - "db"
    networks:
      - scheduleapp
    deploy:
        replicas: 5
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - scheduleapp

networks:
  scheduleapp:
