version: "3.2"

services:
  app:
    image: 'timvisee/hhs-p11-schedulingapp:production'
    ports:
      - "80:5000"
      - "5000:5000"
    environment:
      DATABASE_HOST: "schedulingapp.visee.me"
      DATABASE_DATABASE: "production"
      DATABASE_USER: "sa"
      DATABASE_PASSWORD: "Secret1234!"
      WEB_HOSTS: "http://*:80,http://*:5000"
    depends_on:
      - "db"
    networks:
      - scheduleapp
    deploy:
        replicas: 3

networks:
  scheduleapp:
