version: "3.2"

services:
  app:
    image: 'schedule-app:latest'
    ports:
      - "80:80"
      - "5000:5000"
    environment:
      DATABASE_HOST: "schedulingapp.visee.me"
      DATABASE_DATABASE: "production"
      DATABASE_USER: "sa"
      DATABASE_PASSWORD: "Secret1234!"
      WEB_HOSTS: "http://*:80,http://*:5000"
    depends_on:
      - "db"
    networks:
      - scheduleapp
    deploy:
        replicas: 1
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - scheduleapp

networks:
  scheduleapp:
