version: "2"

services:
  app:
    image: 'schedule-app:latest'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - "db"
    volumes:
      - '../:/app'
  db:
    image: 'microsoft/mssql-server-linux'
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Secret1234
    volumes:
      - 'dbdata:/mnt/drive'
    restart: on_failure

volumes:
  dbdata:
