#!/bin/sh

# Immediately stop the script if an error occurred
set -e

echo "Unpack release image snapshot artifact..."
docker load -i image-artifact.tar.gz

echo "Retag production image..."
docker tag schedule-app:snapshot timvisee/hhs-p11-schedulingapp:production

echo "Login to Docker with user '$DOCKER_LOGIN_USER'..."
echo $DOCKER_LOGIN_PASSWORD | docker login --password-stdin -u $DOCKER_LOGIN_USER 

echo "Push production image to Docker hub..."
docker push timvisee/hhs-p11-schedulingapp:production

echo "Remove artifact image..."
! docker rmi schedule-app:snapshot

echo "Done"
